package service;

import library.FreelingAdapterInterface;
import library.FreelingAdapterSocket;
import org.springframework.stereotype.Service;

import java.io.IOException;

@Service
public class SentenceService {
  private final String HOST = "18.197.54.200";
  private final int PORT = 50005;

  /** Constructor */
  public SentenceService() {}

  /**
   * Returns the solution generated by the FreeLing library
   *
   * @param phrase
   * @return String A string object containing the solution
   * @throws IOException
   */
  public String getSolution(String sentence) throws IOException {
    FreelingAdapterInterface socket = new FreelingAdapterSocket(HOST, PORT);
    String solution = socket.getCorrection(sentence);
    socket.closeConnection();
    return solution;
  }
}
