package it.colletta.service;

import java.io.IOException;
import org.springframework.stereotype.Service;
import it.colletta.library.FreelingAdapterInterface;
import it.colletta.library.FreelingAdapterSocket;

@Service
public class SentenceService {
  private final String host = "18.197.54.200";
  private final int port = 50005;

  /**
   * Constructor SentenceService.
   */
  public SentenceService() {}

  /**
   * Returns the solution generated by the FreeLing library.
   *
   * @param sentence sentence to analyze
   * @return String A string object containing the solution
   * @throws IOException IOException
   */ 
  public String getSolution(String sentence) throws IOException {
    FreelingAdapterInterface socket = new FreelingAdapterSocket(host, port);
    String solution = socket.getCorrection(sentence);
    socket.closeConnection();
    return solution;
  }
}
