package it.colletta.service;

import it.colletta.library.FreelingAdapterInterface;
import it.colletta.library.FreelingAdapterSocket;
import org.springframework.stereotype.Service;

import java.io.IOException;

@Service
public class SentenceService {
  
  private final String host = "18.197.54.200";
  private final int port = 50005;

  /**
   * Constructor.
   */
  public SentenceService() {}

  /**
   * Returns the solution generated by the FreeLing library.
   *
   * @param sentence Sentence.
   * @return String A string object containing the solution.
   * @throws IOException IOException.
   */
  public String getSolution(String sentence) throws IOException {
    FreelingAdapterInterface socket = new FreelingAdapterSocket(this.host, this.port);
    String solution = socket.getCorrection(sentence);
    socket.closeConnection();
    return solution;
  }
}
