/**
 * Label explanation
 * gen_ = generic, they can be used in any component (e.g. navbar, sidebar, footer ecc)
 * *******_ = component specific label, where the asterisks stand for the component label
 */

// eslint-disable-next-line import/prefer-default-export
export const _label = {
  it: {
    account_yourData: 'I tuoi dati',
    dashboard_hiUser: 'Ciao, ',
    executionExercise_complete: 'Completa',
    executionExercise_completeExercise: 'Esercizio',
    executionExercise_mark: 'La tua valutazione: ',
    gen_404Error: 'Errore 404, pagina non trovata',
    gen_account: 'Profilo',
    gen_birthDate: 'Data di nascita',
    gen_dashboard: 'Dashboard',
    gen_email: 'Email',
    gen_firstName: 'Nome',
    gen_lastName: 'Cognome',
    gen_logout: 'Esci',
    gen_modify: 'Modifica',
    gen_newExercise: 'Nuovo esercizio',
    gen_password: 'Password',
    gen_passwordConfirm: 'Conferma password',
    gen_role: 'Ruolo',
    gen_signin: 'Accedi',
    gen_signup: 'Registrati',
    gen_language: 'Lingua',
    gen_admin: 'Amministratore',
    gen_developer: 'Sviluppatore',
    gen_student: 'Studente',
    gen_teacher: 'Insegnante',
    gen_author: 'Autore',
    exercisePreview_execute: "Svolgi l'esercizio",
    gen_it: 'Italiano',
    gen_en: 'Inglese',
    gen_welcome: 'Bentornato',
    gen_userDashboard: 'Pannello Utente',
    gen_phrase: 'Frase',
    gen_insertDone: 'Esercizio aggiunto con successo',
    gen_error: 'Errore interno',
    gen_add: 'Aggiungi',
    gen_new: 'Nuova',
    gen_save: 'Salva',
    gen_edit: 'Modifica',
    gen_delete: 'Elimina',
    gen_reqField: 'Campo obbligatorio',
    gen_opSuccess: 'Operazione completata',
    inputSentence_executeExercise: "Svolgi l'esercizio",
    inputSentence_insertSentence: 'Inserisci la frase',
    insertExercise_ClassDisp: 'Classi disponibili',
    insertExercise_StudentDisp: 'Studenti disponibili ',
    signup_errorPassword: 'Le due passowrd non coincidono',
    signup_selectOption: "Seleziona un'opzione",
    signup_hint:
      'La password deve essere lunga dai 6 ai 20 caratteri e non deve contenere caratteri speciali',
    signUp_completed:
      'Registrazione completata, a breve riceverai per email per confermare il tuo account.',
    signUp_error: 'Registrazione fallita',
    login_error: 'Autenticazione fallita',
    sidebarElementStudent_exercise: 'Esercizi',
    sidebarElementStudent_freeExercise: 'Esercitazione Libera',
    sidebarElementStudent_exercises: 'Compiti per casa',
    sidebarElementStudent_marks: 'I tuoi voti',
    sidebarElementStudent_doneExercises: 'Esercizi Svolti',
    sidebarElementStudent_publicExercises: 'Esercizi Pubblici',
    sidebarElementTeacher_exercise: 'Esercizi',
    sidebarElementTeacher_insertExercise: 'Inserisci esercizio',
    sidebarElementTeacher_exercises: 'Esercizi inseriti',
    sidebarElementTeacher_class: 'Gestione Classi',
    SidebarElementAdministrator_devs: 'Sviluppatori',
    insertExercise_confirmFSolution: 'Inserisci soluzione proposta',
    insertExercise_editFSolution: 'Modifica soluzione',
    gen_devDashboard: 'Pannello Sviluppatore',
    developerDashBoard_desc: 'Filtra e scarica i dati che ti interessano',
    developerDashBoard_devDownText:
      "Premendo il bottone sottostante, puoi scaricare i dati di analisi grammaticale generati dali utenti di Colletta. Potrebbe volerci un po' di tempo, fatti un caffè, dai.",
    developerDashBoard_devDown: 'Scarica',
    adminDashBoard_update: 'Aggiorna',
    developerToAccept_allow: 'Accetta',
    developerToAccept_deny: 'Rifiuta',
    developer_downloadind: 'Download in corso',
    adminDevDashBoard_subtitle:
      'Accetta o rifiuta le richieste di iscrizione degli sviluppatori',
    adminDevDashBoard_noDevApprove: 'Nessun developer da approvare',
    adminDevDashBoard_noUser: 'Nessun utente trovato',
    adminDevDashBoard_devToApprove: 'Sviluppatori da approvare',
    gen_adminUsers: 'Utenti',
    adminUserDashBoard_desc: 'Visualizza e elimina gli utenti',
    adminUserDashBoard_delete: 'Elimina',
    developerDashBoard_action: 'Azioni',
    pagination_first: 'Primo',
    pagination_last: 'Ultimo',
    pagination_prev: 'Precedente',
    pagination_next: 'Successivo',
    exercisePreview_addedOn: 'Aggiunto il',
    classManagement_title: 'Gestione delle classi',
    classCreationModal_name: 'Nome della classe',
    classCreationModal_allStudents: 'Tutti gli studenti',
    classCreationModal_selStudents: 'Studenti selezionati',
    dashboard_done: 'Svolti',
    dashboard_numDone: 'Numero di esercizi svolti',
    dashboard_toDo: 'Da fare',
    dashboard_numToDo: 'Numero di esercizi da fare',
    dashboard_public: 'Pubblici',
    dashboard_numPublic: 'Numbero di esericizi pubblici',
    dashboard_donePercentTitle: 'Compiti svolti',
    dashboard_donePercent: 'Percentuale di compiti svolti',
    adminDashboard_students: 'Studenti',
    adminDashboard_numStudents: 'Numero totale di studenti iscritti al sistema',
    adminDashboard_teachers: 'Insegnanti',
    adminDashboard_numTeachers: 'Numero di insegnanti iscritti al sistema',
    adminDashboard_devs: 'Sviluppatori',
    adminDashboard_numDevs: 'Numero di sviluppatori iscritti al sistema',
    adminDashboard_devWait: 'In Attesa',
    adminDashboard_numDevWait:
      'Numero di sviluppatori in attesa di approvazione'
  },
  en: {
    account_yourData: 'Your data',
    dashboard_hiUser: 'Hello, ',
    executionExercise_complete: 'Submit solution',
    executionExercise_completeExercise: 'Exercise',
    executionExercise_mark: 'Your mark: ',
    gen_404Error: 'Error 404, page not found',
    gen_account: 'Account',
    gen_birthDate: 'Date of birth',
    gen_dashboard: 'Dashboard',
    gen_email: 'Email',
    gen_firstName: 'First Name',
    gen_lastName: 'Last Name',
    gen_logout: 'Logout',
    gen_modify: 'Modify',
    gen_newExercise: 'New Exercise',
    gen_password: 'Password',
    gen_passwordConfirm: 'Confirm password',
    gen_role: 'Role',
    gen_signin: 'Sign In',
    gen_signup: 'Sign Up',
    gen_language: 'Language',
    gen_userDashboard: 'Your Dashboard',
    gen_admin: 'Administrator',
    gen_developer: 'Developer',
    gen_student: 'Student',
    gen_teacher: 'Teacher',
    gen_it: 'Italian',
    gen_en: 'English',
    gen_author: 'Author',
    gen_welcome: 'Welcome',
    gen_phrase: 'Phrase',
    gen_insertDone: 'Successfully added exercise',
    gen_error: 'Internal error',
    gen_add: 'Add',
    gen_new: 'New',
    gen_save: 'Save',
    gen_opSuccess: 'Complete',
    gen_edit: 'Edit',
    gen_delete: 'Delete',
    gen_reqField: 'Required field',
    exercisePreview_execute: 'Execute exercise',
    inputSentence_executeExercise: 'Get to work!',
    inputSentence_insertSentence: 'Enter phrase',
    insertExercise_ClassDisp: 'Classes available',
    insertExercise_StudentDisp: 'Students available',
    signup_errorPassword: 'The two passwords do not match',
    signup_selectOption: 'Select an option',
    signup_hint:
      'Your password must be 6-20 characters long, contain letters and numbers, and must not contain spaces, special characters or emojis',
    signUp_error: 'SignUp error',
    login_error: 'Failed authentication',
    sidebarElementStudent_exercise: 'Your Exercises',
    sidebarElementStudent_freeExercise: 'Free training',
    sidebarElementStudent_exercises: 'Homeworks',
    sidebarElementStudent_marks: 'Your marks',
    sidebarElementStudent_doneExercises: 'Completed Exercises',
    sidebarElementStudent_publicExercises: 'Public Exercises',
    sidebarElementTeacher_exercise: 'Esercise',
    sidebarElementTeacher_insertExercise: 'Insert exercise',
    sidebarElementTeacher_exercises: 'Exercise history',
    sidebarElementTeacher_class: 'Class Management',
    SidebarElementAdministrator_devs: 'Developers',
    insertExercise_confirmFSolution: 'Insert solution',
    insertExercise_editFSolution: 'Edit solution',
    gen_devDashboard: 'Developer Dashboard',
    developerDashBoard_desc: "Filter and download the data you're looking for",
    developerDashBoard_devDownText:
      'By clicking the button below, you can can download all the user generated data of Colletta. This may take a while, feel free to go grab a coffe!',
    developerDashBoard_devDown: 'Download',
    adminDashBoard_update: 'Update',
    developerToAccept_allow: 'Allow',
    developerToAccept_deny: 'Deny',
    developer_downloadind: 'Downloading',
    adminDevDashBoard_subtitle:
      "Approve or deny developers' subscription requests",
    adminDevDashBoard_noDevApprove: 'No developer needs to be approved',
    adminDevDashBoard_devToApprove: 'Developer to Approve',
    gen_adminUsers: 'Users',
    adminUserDashBoard_desc: 'View and delete users',
    adminDevDashBoard_noUser: 'No user found',
    adminUserDashBoard_delete: 'Delete',
    developerDashBoard_action: 'Actions',
    pagination_first: 'First',
    pagination_last: 'Last',
    pagination_prev: 'Previous',
    pagination_next: 'Next',
    exercisePreview_addedOn: 'Added on',
    classManagement_title: 'Class management',
    classCreationModal_name: 'Class name',
    classCreationModal_allStudents: 'All students',
    classCreationModal_selStudents: 'Selected students',
    dashboard_done: 'Done',
    dashboard_numDone: 'Number of done exercises',
    dashboard_toDo: 'To do',
    dashboard_numToDo: 'Number of exercises to be done',
    dashboard_public: 'Public',
    dashboard_numPublic: 'Number of public exercises',
    dashboard_donePercentTitle: 'Done Excercises',
    dashboard_donePercent: 'Done exercises percentage',
    adminDashboard_students: 'Students',
    adminDashboard_numStudents: 'Total number of students in the system',
    adminDashboard_teachers: 'Teachers',
    adminDashboard_numTeachers: 'Total number of teachers in the system',
    adminDashboard_devs: 'Developers',
    adminDashboard_numDevs: 'Total number of developers in the system',
    adminDashboard_devWait: 'Pending',
    adminDashboard_numDevWait: 'Number of developers pending approval'
  }
};
