package service;

import library.FreelingAdapterInterface;
import library.FreelingAdapterSocket;
import org.springframework.stereotype.Service;

import java.io.IOException;

@Service
public class PhraseService {
  private final String HOST = "3.17.205.197";
  private final int PORT = 50005;

  /** Constructor */
  public PhraseService() {}

  /**
   * Returns the solution generated by the FreeLing library
   *
   * @param phrase
   * @return String A string object containing the solution
   * @throws IOException
   */
  public String getSolution(String phrase) throws IOException {
    FreelingAdapterInterface socket = new FreelingAdapterSocket(HOST, PORT);
    String solution = socket.getCorrection(phrase);
    socket.closeConnection();
    return solution;
  }
}
